### ISSUE TITLE
http url in a PATH (perhaps url to be a comment?)

### ISSUE THREAD

**Issue by mastershin** [sglanger/ohif-vagrant#1]
https://github.com/sglanger/ohif-vagrant/blob/ee3f949e77126b36c366a19d561bc10d65d40513/install.sh#L162

**Comment by mastershin** [comment]
Couldn't push the changes (nor pull request) due to permission issue. If you want me to fix this line, let me know. Thanks.

**Comment by sglanger** [comment]
yes, please do


________________________________

**Comment by sglanger** [comment]
I'm trying to make you a collaborator, what is your github account?


________________________________

**Comment by sglanger** [comment]
OK MasterShin

you should be ok to pull/push

________________________________

**Comment by sglanger** [comment]
in case you need this

https://github.com/sglanger/ohif-vagrant/invitations

________________________________

**Comment by mastershin** [comment]
Thank you.
